services:
  - type: web
    name: nutriai
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app_new:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
