services:
  - type: web
    name: nutriai
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app_new:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
